name = "pixiv-cron-worker"
main = "src/index.ts"
compatibility_date = "2024-11-21"

[triggers]
crons = [
  "*/10 * * * *",   # 每10分钟
  "0 1 * * *",      # 每天 01:00
  "0 1 * * 1",      # 每周一 01:00
  "0 1 1 * *"       # 每月1号 01:00
]

[vars]
# 主节点 API（不要以斜杠结尾）。用于获取首页推荐以及触发日/周/月任务
PRIMARY_API_BASE = "https://pixiv.chaosyn.com/api"

# 从节点 API 列表（逗号分隔）。用于分发10分钟任务的单次爬取请求
WORKER_API_BASES = "https://pixiv.chaosyn.com/api"

# 10分钟任务用：目标数量和热度阈值（可选）
TEN_MIN_TARGET_NUM = "100"
TEN_MIN_THRESHOLD = "0.22"

