name = "serverless-pixiv-crawler"
main = "src/index.ts"
compatibility_date = "2024-11-21"

[triggers]
crons = [
  "*/3 * * * *",    # 每3分钟 - 插画推荐和作者推荐任务
  "* * * * *",      # 每1分钟 - 详细信息爬取任务
  "0 1 * * *",      # 每天 01:00 - 每日排行榜
  "0 1 * * 1",      # 每周一 01:00 - 每周排行榜
  "0 1 1 * *"       # 每月1号 01:00 - 每月排行榜
]

[vars]
# 主节点 API（不要以斜杠结尾）。用于获取首页推荐以及触发日/周/月任务
PRIMARY_API_BASE = "https://pixiv.chaosyn.com/api"

# 从节点 API 列表（逗号分隔）。用于分发10分钟任务的单次爬取请求
WORKER_API_BASES = "https://pixiv.chaosyn.com/api"

# 10分钟任务用：目标数量和热度阈值（可选）
TEN_MIN_TARGET_NUM = "100"
TEN_MIN_THRESHOLD = "0"

# 推荐任务popularity过滤阈值（只处理popularity大于此值的插画）
POPULARITY_RECOMMEND = "0.18"

# Supabase配置（用于pic_task表查询）
# 注意：敏感信息应使用 wrangler secret put 命令设置
# SUPABASE_URL = "your-supabase-url"
# SUPABASE_SERVICE_ROLE_KEY = "your-service-role-key"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
